"""
RegLIP Model: Enhancing Vision-Language Embeddings through Regression-Based Contrastive Learning

This module implements the RegLIP model based on SigLIP architecture.
"""

import math
from dataclasses import dataclass
from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from .config import RegLIPConfig
from .text import RegLIPTextModel
from .vision import RegLIPVisionModel


@dataclass
class RegLIPOutput:
    """
    RegLIP model outputs.
    
    Args:
        loss (`torch.FloatTensor` of shape `(1,)`, *optional*, returned when `return_loss` is `True`):
            Regression-based contrastive loss for image-text similarity.
        logits_per_image (`torch.FloatTensor` of shape `(image_batch_size, text_batch_size)`):
            The scaled dot product scores between `image_embeds` and `text_embeds`. This represents the image-text
            similarity scores.
        logits_per_text (`torch.FloatTensor` of shape `(text_batch_size, image_batch_size)`):
            The scaled dot product scores between `text_embeds` and `image_embeds`. This represents the text-image
            similarity scores.
        similarity_targets (`torch.FloatTensor` of shape `(batch_size, batch_size)`, *optional*):
            Continuous similarity targets generated by the frozen text encoder.
        text_embeds (`torch.FloatTensor` of shape `(batch_size, output_dim)`):
            The text embeddings obtained by applying the projection layer to the pooled output of RegLIPTextModel.
        image_embeds (`torch.FloatTensor` of shape `(batch_size, output_dim)`):
            The image embeddings obtained by applying the projection layer to the pooled output of RegLIPVisionModel.
    """
    
    loss: Optional[torch.FloatTensor] = None
    logits_per_image: Optional[torch.FloatTensor] = None
    logits_per_text: Optional[torch.FloatTensor] = None
    similarity_targets: Optional[torch.FloatTensor] = None
    text_embeds: Optional[torch.FloatTensor] = None
    image_embeds: Optional[torch.FloatTensor] = None


class RegLIPModel(nn.Module):
    """
    RegLIP model for vision-language understanding using regression-based contrastive learning.
    
    This model is based on SigLIP architecture but replaces the binary classification loss
    with a regression loss using continuous similarity scores.
    """
    
    def __init__(self, config: RegLIPConfig):
        super().__init__()
        self.config = config
        
        # Initialize text and vision models
        self.text_model = RegLIPTextModel(config.text_config)
        self.vision_model = RegLIPVisionModel(config.vision_config)
        
        # Initialize scale and bias parameters (like SigLIP)
        # SigLIP uses shape [1] tensors, not scalars
        self.logit_scale = nn.Parameter(torch.tensor([config.logit_scale_init_value]))
        self.logit_bias = nn.Parameter(torch.tensor([config.logit_bias_init_value]))
        
        # For similarity target generation (frozen text encoder)
        self.frozen_text_encoder = None
    
    def set_frozen_text_encoder(self, frozen_encoder):
        """Set the frozen text encoder for similarity target generation.

        Accepts any BaseEmbeddingModel instance (new unified interface),
        as well as legacy sentence-transformer or QwenEmbeddingClient objects.
        """
        from .embeddings.base import BaseEmbeddingModel

        if isinstance(frozen_encoder, BaseEmbeddingModel):
            self.frozen_text_encoder = frozen_encoder
            self.encoder_type = 'embedding_model'
        elif hasattr(frozen_encoder, 'encode'):
            # Legacy: sentence transformer model
            self.frozen_text_encoder = frozen_encoder
            self.encoder_type = 'sentence_transformer'
        elif hasattr(frozen_encoder, 'get_embeddings'):
            # Legacy: old QwenEmbeddingClient
            self.frozen_text_encoder = frozen_encoder
            self.encoder_type = 'qwen_client'
        else:
            raise ValueError("Encoder must be a BaseEmbeddingModel, sentence transformer, or QwenEmbeddingClient")

        # Freeze all parameters (only applies to sentence transformers)
        if hasattr(self.frozen_text_encoder, 'parameters'):
            for param in self.frozen_text_encoder.parameters():
                param.requires_grad = False
    
    def get_text_features(
        self,
        input_ids: torch.LongTensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        output_attentions: bool = False,
        output_hidden_states: bool = False,
    ) -> torch.FloatTensor:
        """Extract text features."""
        text_outputs = self.text_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
        )
        
        return text_outputs[1]  # pooled output
    
    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        output_attentions: bool = False,
        output_hidden_states: bool = False,
        interpolate_pos_encoding: bool = False,
    ) -> torch.FloatTensor:
        """Extract image features."""
        vision_outputs = self.vision_model(
            pixel_values=pixel_values,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            interpolate_pos_encoding=interpolate_pos_encoding,
        )
        
        return vision_outputs[1]  # pooled output
    
    def generate_similarity_targets(
        self, texts: list, images: list = None,
    ) -> torch.FloatTensor:
        """
        Generate continuous similarity targets using the frozen encoder.

        If the encoder supports images and ``images`` is provided, produces
        **cross-modal** targets (image-text cosine similarity).  Otherwise
        falls back to **text-text** similarity.

        Args:
            texts: List of text strings.
            images: Optional list of raw image bytes (JPEG/PNG).  Only used
                    when the frozen encoder supports image embeddings.

        Returns:
            Similarity matrix with values between 0 and 1,
            shape ``(batch, batch)``.
        """
        if self.frozen_text_encoder is None:
            raise ValueError("Frozen text encoder not set. Call set_frozen_text_encoder() first.")

        device = next(self.parameters()).device

        # --- Encode texts ------------------------------------------------
        if self.encoder_type == 'embedding_model':
            text_emb_np = self.frozen_text_encoder.get_embeddings(texts, batch_size=32)
            text_embeddings = torch.from_numpy(text_emb_np).float().to(device)
        elif self.encoder_type == 'sentence_transformer':
            with torch.no_grad():
                text_embeddings = self.frozen_text_encoder.encode(
                    texts, convert_to_tensor=True, device=device,
                )
        elif self.encoder_type == 'qwen_client':
            text_emb_np = self.frozen_text_encoder.get_embeddings(texts, batch_size=32)
            text_embeddings = torch.from_numpy(text_emb_np).float().to(device)
        else:
            raise ValueError(f"Unsupported encoder type: {self.encoder_type}")

        text_embeddings = F.normalize(text_embeddings, p=2, dim=1)

        # --- Cross-modal targets (image-text) if encoder supports it -----
        use_cross_modal = (
            images is not None
            and self.encoder_type == 'embedding_model'
            and self.frozen_text_encoder.supports_images
        )

        if use_cross_modal:
            img_emb_np = self.frozen_text_encoder.get_image_embeddings(images, batch_size=8)
            image_embeddings = torch.from_numpy(img_emb_np).float().to(device)
            image_embeddings = F.normalize(image_embeddings, p=2, dim=1)
            # Cross-modal similarity: each row i = similarity of image_i to all texts
            similarity_matrix = torch.matmul(image_embeddings, text_embeddings.t())
        else:
            # Text-text similarity (original behaviour)
            similarity_matrix = torch.matmul(text_embeddings, text_embeddings.t())

        # Scale from [-1, 1] to [0, 1]
        similarity_matrix = (similarity_matrix + 1) / 2

        return similarity_matrix
    
    def binary_contrastive_loss(
        self,
        logits_per_text: torch.FloatTensor,
    ) -> torch.FloatTensor:
        """
        Compute SigLIP's binary contrastive loss for comparison.
        
        Args:
            logits_per_text: Predicted similarity logits [batch_size, batch_size]
            
        Returns:
            Binary contrastive loss
        """
        # SigLIP's binary loss implementation
        batch_size = logits_per_text.size(0)
        device = logits_per_text.device
        
        # Create binary targets (diagonal = 1, off-diagonal = 0)
        eye = torch.eye(batch_size, device=device)
        m1_diag1 = -torch.ones_like(logits_per_text) + 2 * eye
        
        # Compute log-sigmoid loss
        loglik = F.logsigmoid(m1_diag1 * logits_per_text)
        nll = -torch.sum(loglik, dim=-1)
        loss = nll.mean()
        
        return loss
    
    def regression_contrastive_loss(
        self,
        text_embeds: torch.FloatTensor,
        image_embeds: torch.FloatTensor,
        similarity_targets: torch.FloatTensor,
    ) -> torch.FloatTensor:
        """
        Compute regression-based contrastive loss using raw cosine similarity.
        
        This is the core of RegLIP: instead of binary classification (0/1), we use 
        continuous similarity scores as targets and train the model to predict these 
        with Mean Squared Error.
        
        Key design choice (Option 3 - cleanest for research):
        - Use raw cosine similarity without learned scale/bias
        - Map cosine similarity from [-1, 1] to [0, 1] using linear transformation
        - This isolates the effect of soft labels from other factors
        
        Args:
            text_embeds: Normalized text embeddings [batch_size, embed_dim]
            image_embeds: Normalized image embeddings [batch_size, embed_dim]
            similarity_targets: Ground truth text-text similarities [batch_size, batch_size]
            
        Returns:
            Regression loss (MSE)
        """
        # Compute raw cosine similarity (embeddings are already L2-normalized)
        # This gives values in [-1, 1]
        cosine_sim = torch.matmul(text_embeds, image_embeds.t())
        
        # Map cosine similarity from [-1, 1] to [0, 1] range
        # This matches the range of similarity_targets (which are also in [0, 1])
        predicted_similarities = (cosine_sim + 1) / 2
        
        # Compute MSE loss between predicted and target similarities
        loss = F.mse_loss(predicted_similarities, similarity_targets)
        
        return loss
    
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.FloatTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        return_loss: Optional[bool] = None,
        texts: Optional[list] = None,
        raw_images: Optional[list] = None,
        similarity_targets: Optional[torch.FloatTensor] = None,
        use_regression_loss: bool = True,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        interpolate_pos_encoding: bool = False,
    ) -> RegLIPOutput:
        """
        Forward pass of RegLIP model.
        
        Args:
            input_ids: Text token ids
            pixel_values: Image pixel values
            attention_mask: Text attention mask
            position_ids: Text position ids
            return_loss: Whether to compute loss
            texts: List of text strings for similarity target generation
            raw_images: Optional list of raw image bytes for cross-modal targets
            similarity_targets: Pre-computed similarity targets
            use_regression_loss: Whether to use regression or binary loss
            output_attentions: Whether to output attention weights
            output_hidden_states: Whether to output hidden states
            interpolate_pos_encoding: Whether to interpolate position encodings
            
        Returns:
            RegLIPOutput containing logits_per_text, logits_per_image, loss, similarity_targets, image_embeds, text_embeds
        """
        # Get text features
        text_outputs = self.text_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
        )
        
        # Get image features
        vision_outputs = self.vision_model(
            pixel_values=pixel_values,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            interpolate_pos_encoding=interpolate_pos_encoding,
        )
        
        image_embeds = vision_outputs[1]  # pooled output
        text_embeds = text_outputs[1]    # pooled output
        
        # Ensure we have 2D tensors
        if len(image_embeds.shape) > 2:
            image_embeds = image_embeds.squeeze()
        if len(text_embeds.shape) > 2:
            text_embeds = text_embeds.squeeze()
        
        # Normalize features (like SigLIP)
        image_embeds = F.normalize(image_embeds, p=2, dim=-1)
        text_embeds = F.normalize(text_embeds, p=2, dim=-1)
        
        # Compute cosine similarity as logits
        logits_per_text = torch.matmul(text_embeds, image_embeds.t())
        
        # Apply temperature and bias (like SigLIP)
        logits_per_text = logits_per_text * self.logit_scale.exp() + self.logit_bias
        logits_per_image = logits_per_text.t()
        
        loss = None
        if return_loss:
            if use_regression_loss:
                # Generate similarity targets if not provided
                if similarity_targets is None and texts is not None:
                    similarity_targets = self.generate_similarity_targets(texts, images=raw_images)
                
                if similarity_targets is not None:
                    # Use raw cosine similarity (embeddings) for regression loss
                    # This avoids the sigmoid/scale/bias issue that caused model collapse
                    loss = self.regression_contrastive_loss(text_embeds, image_embeds, similarity_targets)
                else:
                    raise ValueError("For regression loss, either similarity_targets or texts must be provided")
            else:
                # Use binary contrastive loss (SigLIP-style)
                loss = self.binary_contrastive_loss(logits_per_text)
        
        return RegLIPOutput(
            loss=loss,
            logits_per_image=logits_per_image,
            logits_per_text=logits_per_text,
            similarity_targets=similarity_targets,
            image_embeds=image_embeds,
            text_embeds=text_embeds,
        ) 